BOARD_TAG     = mega2560
MONITOR_PORT  = /dev/ttyS3
ARDUINO_LIBS = Wire EEPROM LiquidCrystal AFMotor
USER_LIB_PATH = ./libraries/
ARDUINO_DIR   = /home/mwvent/projects/arduino-1.0.6/
# Download Arduino-Makefile from https://github.com/sudar/Arduino-Makefile and include the path to Arduino.mk here

include ./Arduino-Makefile/Arduino.mk