BOARD_TAG     = mega2560
MONITOR_PORT  = /dev/ttyS3
ARDUINO_LIBS = Wire EEPROM LiquidCrystal AFMotor
USER_LIB_PATH = ./libraries/
ARDUINO_DIR   = /home/mwvent/projects/arduino-1.0.6/
include ./Arduino-Makefile/Arduino.mk